// server/utils/generatePDF.js
const puppeteer = require('puppeteer');

const generatePDF = async (html, options = {}) => {
  let browser;
  try {
    browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
      ...options
    });
    return pdf;
  } finally {
    if (browser) await browser.close();
  }
};

// Generate monthly expense report HTML
const generateExpenseReportHTML = (user, groups, expenses, month, year) => {
  const totalSpent = expenses.reduce((s, e) => s + e.amount, 0);
  const byCategory = {};
  expenses.forEach(e => {
    byCategory[e.category] = (byCategory[e.category] || 0) + e.amount;
  });

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; color: #1a1a2e; padding: 20px; }
        .header { background: linear-gradient(135deg, #1a1a2e, #16213e); color: #00d4ff; padding: 30px; border-radius: 12px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 28px; }
        .header p { margin: 5px 0 0; opacity: 0.7; }
        .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 24px; }
        .stat { background: #f8f9fa; border-radius: 8px; padding: 16px; text-align: center; }
        .stat .value { font-size: 24px; font-weight: bold; color: #1a1a2e; }
        .stat .label { font-size: 12px; color: #666; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #1a1a2e; color: #00d4ff; padding: 10px 12px; text-align: left; font-size: 13px; }
        td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 13px; }
        tr:nth-child(even) td { background: #f8f9fa; }
        .footer { margin-top: 32px; text-align: center; color: #999; font-size: 11px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>💰 FinBuddy — Monthly Report</h1>
        <p>${user.name} • ${month} ${year}</p>
      </div>

      <div class="stats">
        <div class="stat">
          <div class="value">₹${totalSpent.toLocaleString('en-IN')}</div>
          <div class="label">Total Spent</div>
        </div>
        <div class="stat">
          <div class="value">${expenses.length}</div>
          <div class="label">Transactions</div>
        </div>
        <div class="stat">
          <div class="value">${groups.length}</div>
          <div class="label">Active Groups</div>
        </div>
      </div>

      <h3>Spending by Category</h3>
      <table>
        <thead><tr><th>Category</th><th>Amount</th><th>% of Total</th></tr></thead>
        <tbody>
          ${Object.entries(byCategory).map(([cat, amt]) => `
            <tr>
              <td style="text-transform:capitalize">${cat}</td>
              <td>₹${amt.toLocaleString('en-IN')}</td>
              <td>${((amt / totalSpent) * 100).toFixed(1)}%</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h3 style="margin-top:24px">Recent Transactions</h3>
      <table>
        <thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th></tr></thead>
        <tbody>
          ${expenses.slice(0, 20).map(e => `
            <tr>
              <td>${new Date(e.date).toLocaleDateString('en-IN')}</td>
              <td>${e.description}</td>
              <td style="text-transform:capitalize">${e.category}</td>
              <td>₹${e.amount.toLocaleString('en-IN')}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        <p>Generated by FinBuddy on ${new Date().toLocaleDateString('en-IN')} • For educational purposes only</p>
      </div>
    </body>
    </html>
  `;
};

// Generate trade certificate HTML
const generateTradeCertificateHTML = (user, stats) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Georgia, serif; background: #0d0d1a; color: white; padding: 40px; margin: 0; }
        .cert { border: 3px solid #00d4ff; border-radius: 16px; padding: 40px; text-align: center; background: linear-gradient(135deg, #1a1a2e, #16213e); }
        h1 { color: #00d4ff; font-size: 32px; margin: 0 0 8px; }
        .emoji { font-size: 64px; margin: 16px 0; }
        .name { font-size: 28px; font-weight: bold; color: #00ff88; margin: 16px 0; }
        .stats { display: grid; grid-template-columns: repeat(3,1fr); gap: 16px; margin: 24px 0; }
        .stat { background: rgba(255,255,255,0.05); border-radius: 8px; padding: 12px; }
        .stat .v { font-size: 22px; font-weight: bold; color: #00d4ff; }
        .stat .l { font-size: 11px; color: #aaa; margin-top: 4px; }
        .footer { margin-top: 24px; color: #aaa; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="cert">
        <h1>🏆 FinBuddy Trading Certificate</h1>
        <div class="emoji">📈</div>
        <p style="color:#aaa">This certifies that</p>
        <div class="name">${user.name}</div>
        <p style="color:#aaa">has completed virtual trading on FinBuddy</p>
        <div class="stats">
          <div class="stat"><div class="v">${stats.totalTrades}</div><div class="l">Total Trades</div></div>
          <div class="stat"><div class="v">${stats.winRate}%</div><div class="l">Win Rate</div></div>
          <div class="stat"><div class="v">${stats.finScore}</div><div class="l">FinScore</div></div>
        </div>
        <div class="footer">Issued: ${new Date().toLocaleDateString('en-IN')} • FinBuddy — Learn Finance Together</div>
      </div>
    </body>
    </html>
  `;
};

// Generate annual review HTML
const generateAnnualReviewHTML = (user, data) => {
  const assets = data.assets || {};
  const assetAlloc = [
    { name: 'Cash', value: assets.cash || 0 },
    { name: 'Stocks', value: assets.stocks || 0 },
    { name: 'Crypto', value: assets.crypto || 0 },
  ].filter(d => d.value > 0);

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; padding: 30px; line-height: 1.6; }
        .header { background: linear-gradient(135deg, #4f46e5, #06b6d4); color: white; padding: 35px; border-radius: 16px; margin-bottom: 30px; text-align: center; }
        .header h1 { margin: 0; font-size: 32px; letter-spacing: -0.5px; }
        .header p { margin: 8px 0 0; opacity: 0.9; font-size: 16px; }
        .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 30px; }
        .stat-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 18px; text-align: center; }
        .stat-card .val { font-size: 20px; font-weight: 800; color: #0f172a; margin-bottom: 4px; }
        .stat-card .lbl { font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: 600; }
        .section-title { font-size: 18px; font-weight: 700; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { background: #0f172a; color: #38bdf8; padding: 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; color: #334155; }
        tr:nth-child(even) td { background: #f8fafc; }
        .badge { background: #dbeafe; color: #1e40af; padding: 3px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
        .insight-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 12px; padding: 20px; margin-top: 30px; }
        .insight-box h4 { margin: 0 0 8px; color: #166534; font-size: 16px; display: flex; items-center: center; }
        .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 11px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📊 FinBuddy Annual Wealth Review</h1>
        <p>Comprehensive Net Worth & Portfolio Statement • ${user.name}</p>
      </div>

      <div class="stats-grid">
        <div class="stat-card">
          <div class="val" style="color: #06b6d4;">₹${(data.netWorth || 0).toLocaleString('en-IN')}</div>
          <div class="lbl">Net Worth</div>
        </div>
        <div class="stat-card">
          <div class="val" style="color: #10b981;">₹${(assets.total || 0).toLocaleString('en-IN')}</div>
          <div class="lbl">Total Assets</div>
        </div>
        <div class="stat-card">
          <div class="val" style="color: #ef4444;">₹${(data.liabilities || 0).toLocaleString('en-IN')}</div>
          <div class="lbl">Liabilities</div>
        </div>
        <div class="stat-card">
          <div class="val" style="color: #6366f1;">${data.fiScore || 0}/100</div>
          <div class="lbl">FI Score</div>
        </div>
      </div>

      <div class="section-title">💼 Asset Allocation Breakdown</div>
      <table>
        <thead>
          <tr>
            <th>Asset Category</th>
            <th>Value (INR)</th>
            <th>Percentage Allocation</th>
          </tr>
        </thead>
        <tbody>
          ${assetAlloc.map(a => `
            <tr>
              <td style="font-weight: 600;">${a.name}</td>
              <td>₹${a.value.toLocaleString('en-IN')}</td>
              <td><span class="badge">${((a.value / (assets.total || 1)) * 100).toFixed(1)}%</span></td>
            </tr>
          `).join('')}
          ${assetAlloc.length === 0 ? '<tr><td colspan="3" style="text-align: center; color: #94a3b8;">No assets registered.</td></tr>' : ''}
        </tbody>
      </table>

      ${data.emis && data.emis.length > 0 ? `
        <div class="section-title">💳 Outstanding Liabilities & EMIs</div>
        <table>
          <thead>
            <tr>
              <th>Loan/EMI Name</th>
              <th>Principal Amount</th>
              <th>Monthly Premium</th>
              <th>Interest Rate</th>
              <th>Tenure</th>
            </tr>
          </thead>
          <tbody>
            ${data.emis.map(e => `
              <tr>
                <td style="font-weight: 600;">${e.name}</td>
                <td>₹${parseInt(e.principal || 0).toLocaleString('en-IN')}</td>
                <td style="color: #ef4444; font-weight: 600;">₹${(e.emi || 0).toLocaleString('en-IN')}</td>
                <td>${e.annualRate}%</td>
                <td>${e.tenureMonths} Months</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}

      <div class="insight-box">
        <h4>💡 FinBuddy Personalized Wealth Insights</h4>
        <p style="margin: 0; font-size: 13px; color: #1e3a1e;">
          Based on your Financial Independence (FI) Score of <strong>${data.fiScore || 0}/100</strong>:
          ${data.fiScore >= 75 ? 'You are in excellent financial health! Maintain your robust asset diversification and continue minimizing high-interest consumer debt to speed up full retirement independence.' :
            data.fiScore >= 50 ? 'Your momentum is strong. Consider systematically investing cash buffers exceeding 6 months of living expenses into equity mutual funds to fight long-term inflation.' :
            data.fiScore >= 25 ? 'You are actively building momentum. Make sure to map out outstanding EMIs, and focus on paying down any high-interest debt aggressively to balance your leverage ratio.' :
            'You are just starting your wealth journey! Focus on setting up regular virtual stock and mutual fund SIPs inside FinBuddy to practice consistent wealth compounding.'
          }
        </p>
      </div>

      <div class="footer">
        <p>Generated automatically on ${new Date().toLocaleDateString('en-IN')} by FinBuddy Wealth Engine.</p>
        <p style="opacity: 0.7; margin-top: 5px;">This report is a simulated review based on virtual balances and tracked records inside the FinBuddy platform.</p>
      </div>
    </body>
    </html>
  `;
};

// Generate transaction invoice HTML
const generateInvoiceHTML = (user, inv) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: 'Segoe UI', Roboto, sans-serif; color: #1e293b; padding: 30px; line-height: 1.5; background: #fff; }
        .invoice-box { max-width: 800px; margin: auto; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 26px; font-weight: 900; background: linear-gradient(135deg, #7c3aed, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .company-details { text-align: right; font-size: 12px; color: #64748b; line-height: 1.4; }
        .meta-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; margin-bottom: 40px; }
        .bill-to h3 { font-size: 11px; text-transform: uppercase; tracking-wider; color: #94a3b8; margin: 0 0 8px; }
        .bill-to p { margin: 0; font-size: 14px; font-weight: 700; color: #0f172a; }
        .bill-to span { font-size: 13px; color: #64748b; }
        .inv-details { text-align: right; }
        .inv-details h3 { font-size: 18px; font-weight: 900; color: #0f172a; margin: 0 0 6px; }
        .inv-details p { margin: 2px 0; font-size: 13px; color: #64748b; }
        .inv-details span { font-weight: 600; color: #0f172a; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th { background: #f8fafc; color: #475569; padding: 12px; font-size: 11px; text-transform: uppercase; font-weight: 700; border-bottom: 1px solid #e2e8f0; }
        td { padding: 14px 12px; border-bottom: 1px solid #f1f5f9; font-size: 13px; color: #334155; }
        .total-box { margin-left: auto; width: 250px; margin-top: 20px; font-size: 14px; }
        .total-row { display: flex; justify-content: space-between; padding: 6px 0; }
        .total-row.grand { border-top: 2px solid #e2e8f0; padding-top: 10px; font-size: 18px; font-weight: 900; color: #7c3aed; }
        .paid-stamp { display: inline-block; border: 3px solid #10b981; color: #10b981; font-weight: 900; text-transform: uppercase; padding: 6px 16px; border-radius: 8px; font-size: 16px; transform: rotate(-5deg); margin-top: 20px; opacity: 0.85; }
        .footer { margin-top: 60px; text-align: center; color: #94a3b8; font-size: 11px; border-top: 1px solid #f1f5f9; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="invoice-box">
        <div class="header">
          <div>
            <div class="logo">💰 FinBuddy Elite</div>
            <p style="margin: 4px 0 0; font-size: 13px; color: #64748b;">Gamified Financial Accelerator</p>
          </div>
          <div class="company-details">
            <p><strong>FinBuddy Technologies Pvt Ltd</strong></p>
            <p>Academic Incubation Center, IIT Bombay</p>
            <p>Mumbai, Maharashtra, India</p>
            <p>billing@finbuddy.edu</p>
          </div>
        </div>

        <div class="meta-grid">
          <div class="bill-to">
            <h3>Billed To</h3>
            <p>${user.name}</p>
            <span>${user.email}</span><br>
            <span>College: ${user.college || 'Verified Member'}</span>
          </div>
          <div class="inv-details">
            <h3>TAX INVOICE</h3>
            <p>Invoice No: <span>${inv.id}</span></p>
            <p>Date: <span>${inv.date}</span></p>
            <p>Payment Mode: <span>UPI / Netbanking</span></p>
            <p>Status: <span style="color: #10b981; font-weight: 800;">PAID</span></p>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th style="text-align: left; width: 60%;">Description</th>
              <th style="text-align: center;">Qty</th>
              <th style="text-align: right;">Unit Price</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="font-weight: 600;">
                FinBuddy Elite VIP Membership (1 Year Access)<br>
                <span style="font-size: 11px; color: #64748b; font-weight: normal;">
                  Includes Unlimited AI Coach consultations, Premium Battle lobby access, and advanced Portfolio metrics.
                </span>
              </td>
              <td style="text-align: center;">1</td>
              <td style="text-align: right;">₹299.00</td>
              <td style="text-align: right; font-weight: 600;">₹299.00</td>
            </tr>
          </tbody>
        </table>

        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <div class="paid-stamp">PAID</div>
            <p style="font-size: 11px; color: #94a3b8; margin-top: 15px; font-family: monospace;">
              Transaction Ref: ${inv.gatewayId}<br>
              Order Ref: ${inv.orderId || 'ord_elite_auto'}
            </p>
          </div>
          <div class="total-box">
            <div class="total-row">
              <span style="color: #64748b;">Subtotal:</span>
              <span>₹299.00</span>
            </div>
            <div class="total-row">
              <span style="color: #64748b;">IGST (0%):</span>
              <span>₹0.00</span>
            </div>
            <div class="total-row grand">
              <span>Grand Total:</span>
              <span>₹299.00</span>
            </div>
          </div>
        </div>

        <div class="footer">
          <p>Thank you for subscribing to FinBuddy Elite! This is a computer-generated invoice and does not require a physical signature.</p>
          <p style="opacity: 0.7; margin-top: 4px;">FinBuddy • Incubating Financial Literacy in Campus Lobbies.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

module.exports = { 
  generatePDF, 
  generateExpenseReportHTML, 
  generateTradeCertificateHTML, 
  generateAnnualReviewHTML,
  generateInvoiceHTML
};
